### ISSUE TITLE
资源没关闭

### ISSUE THREAD

**Issue by qq839924354** [MrZhousf/OkHttp3#5]
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                               java.lang.Throwable: Explicit termination method 'close' not called
                                                                   at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                                   at java.io.FileOutputStream.<init>(FileOutputStream.java:89)
                                                                   at okio.Okio.appendingSink(Okio.java:185)
                                                                   at okhttp3.internal.io.FileSystem$1.appendingSink(FileSystem.java:59)
                                                                   at okhttp3.internal.cache.DiskLruCache.newJournalWriter(DiskLruCache.java:314)
                                                                   at okhttp3.internal.cache.DiskLruCache.readJournal(DiskLruCache.java:306)
                                                                   at okhttp3.internal.cache.DiskLruCache.initialize(DiskLruCache.java:227)
                                                                   at okhttp3.internal.cache.DiskLruCache.get(DiskLruCache.java:435)
                                                                   at okhttp3.Cache.get(Cache.java:194)
                                                                   at okhttp3.Cache$1.get(Cache.java:144)
                                                                   at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:54)
                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                   at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                   at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                   at com.okhttplib.helper.BaseHelper$1.intercept(BaseHelper.java:79)
                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                   at com.okhttplib.OkHttpUtil$4.intercept(OkHttpUtil.java:314)
                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                   at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
                                                                   at okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
                                                                   at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                   at java.lang.Thread.run(Thread.java:818)

**Comment by MrZhousf** [comment]
你好，该bug已在okhttp官方有反馈，详情：https://github.com/square/okhttp/issues/3174

**Comment by qq839924354** [comment]
谢谢，有什么好的办法避免

**Comment by MrZhousf** [comment]
请引用最新版本 compile 'com.zhousf.lib:okhttp3:2.6.3'
在Application中OkHttpUtil.init(this) .setShowHttpLog(false);//关闭日志
针对该问题我会及时关注okhttp官方的动态进行相应更新。

**Comment by qq839924354** [comment]
谢谢
