### ISSUE TITLE
日志拦截器 null

### ISSUE THREAD

**Issue by qq839924354** [MrZhousf/OkHttp3#6]
我在weTest 三次测试150台手机 ，几部6.0的手机都发现日志拦截器出错，也设置了.setShowHttpLog(false) 还是出错
TIME=1453711032000
FINGERPRINT=qcom/msm8226/msm8226:4.3/JLS36C/eng.android.20160125.163608:user/test-keys
HARDWARE=qcom
UNKNOWN=unknown
RADIO=unknown
BOARD=MSM8226
versionCode=6
PRODUCT=GiONEE
versionName=6.1
DISPLAY=amigo2.2.5
USER=android
HOST=desktop
DEVICE=GiONEE
TAGS=test-keys
MODEL=GN9000L
BOOTLOADER=unknown
CPU_ABI=armeabi-v7a
CPU_ABI2=armeabi
IS_DEBUGGABLE=false
ID=JLS36C
SERIAL=4193451c
MANUFACTURER=GiONEE
BRAND=GiONEE
TYPE=user
java.lang.NullPointerException
        at okhttp3.internal.io.FileSystem$1.sink(FileSystem.java:52)
        at okhttp3.internal.cache.DiskLruCache.rebuildJournal(DiskLruCache.java:395)
        at okhttp3.internal.cache.DiskLruCache.initialize(DiskLruCache.java:245)
        at okhttp3.internal.cache.DiskLruCache.get(DiskLruCache.java:435)
        at okhttp3.Cache.get(Cache.java:194)
        at okhttp3.Cache$1.get(Cache.java:144)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:54)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at com.okhttplib.helper.BaseHelper$1.intercept(BaseHelper.java:80)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at com.okhttplib.OkHttpUtil$4.intercept(OkHttpUtil.java:314)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
        at java.lang.Thread.run(Thread.java:841)

-----------------------

**Comment by MrZhousf** [comment]
请升级到最新的版本号试试

**Comment by qq839924354** [comment]
谢谢

**Comment by qq839924354** [comment]
今天换成你最新的了，compile 'com.zhousf.lib:okhttp3:2.6.7.4' 也打开了日志。测试了30台手机，还发现一台有日志问题的。
TIME=1433831978000
FINGERPRINT=vivo/msm8974/msm8974:4.4.2/KVT49L/eng.compiler.20150609.142956:user/dev-keys
HARDWARE=qcom
UNKNOWN=unknown
RADIO=0.1.c1.22-00003-M8974AAAAANPZM-1
BOARD=MSM8974
versionCode=6
PRODUCT=msm8974
versionName=6.3
DISPLAY=KVT49L dev-keys
USER=compiler
HOST=compiler024
DEVICE=msm8974
TAGS=dev-keys
MODEL=vivo Xplay3S
BOOTLOADER=unknown
CPU_ABI=armeabi-v7a
CPU_ABI2=armeabi
IS_DEBUGGABLE=false
ID=KVT49L
SERIAL=1786826d
MANUFACTURER=BBK
BRAND=vivo
TYPE=user
java.lang.NullPointerException
        at okhttp3.internal.io.FileSystem$1.sink(FileSystem.java:52)
        at okhttp3.internal.cache.DiskLruCache.rebuildJournal(DiskLruCache.java:395)
        at okhttp3.internal.cache.DiskLruCache.initialize(DiskLruCache.java:245)
        at okhttp3.internal.cache.DiskLruCache.get(DiskLruCache.java:435)
        at okhttp3.Cache.get(Cache.java:194)
        at okhttp3.Cache$1.get(Cache.java:144)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:54)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at com.okhttplib.OkHttpUtil$5.intercept(OkHttpUtil.java:354)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)

**Comment by qq839924354** [comment]
又使用真机远程调试没出现上面的问题。可能是偶尔的。

**Comment by qq839924354** [comment]
是不是Environment.getExternalStorageDirectory().getPath()+"/okHttp_download/"; 在6.0以上要动态申请权限啊

**Comment by MrZhousf** [comment]
6.0以上动态申请权限DEMO中的BaseActivity中有实现，请参考做出相应修改即可！

**Comment by qq839924354** [comment]
谢谢，一致的支持。

**Comment by qq839924354** [comment]
我发现问题还是存在的，都是4.4.2的系统，异步的 OkHttpUtil.getDefault(this).doGetAsync都出现问题。
我也用你原生的工程在wetest真机vivoXplay3S（4.4.2）测试，异步异常退出。
删除了  .addInterceptor(CACHE_CONTROL_INTERCEPTOR)也一样异常退出。
MODEL=vivo Xplay3S
BOOTLOADER=unknown
CPU_ABI=armeabi-v7a
CPU_ABI2=armeabi
IS_DEBUGGABLE=false
ID=KVT49L
SERIAL=1786826d
MANUFACTURER=BBK
BRAND=vivo
TYPE=user
java.lang.NullPointerException
        at okhttp3.internal.io.FileSystem$1.sink(FileSystem.java:52)
        at okhttp3.internal.cache.DiskLruCache.rebuildJournal(DiskLruCache.java:395)
        at okhttp3.internal.cache.DiskLruCache.initialize(DiskLruCache.java:245)
        at okhttp3.internal.cache.DiskLruCache.get(DiskLruCache.java:435)
        at okhttp3.Cache.get(Cache.java:194)
        at okhttp3.Cache$1.get(Cache.java:144)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:54)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at com.okhttplib.OkHttpUtil$5.intercept(OkHttpUtil.java:354)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)

**Comment by MrZhousf** [comment]
请在Applicaiton全局设置中将缓存设置为网络试下，等待你的回复。
.setCacheType(CacheType.FORCE_NETWORK)//缓存类型

**Comment by qq839924354** [comment]
.setCacheType(CacheType.FORCE_NETWORK)//缓存类型  用你原生的工程在wetest真机vivoXplay3S（4.4.2）测试还是异常的退出，等下我用我的工程测试，我的工具添加了UncaughtExceptionHandler异常传回服务器的。

**Comment by qq839924354** [comment]
刚刚在你的源码上测试金立的4.3，应该是没网络的。由于vivoXplay3S 4.4.2一直用人占用。测试的过程在
http://pan.baidu.com/s/1nv9HCpz

**Comment by MrZhousf** [comment]
感谢你的测试视频分享，请升级至最新版本后再用vivoXplay3S 4.4.2进行测试。最好贴上日志报告。

**Comment by qq839924354** [comment]
由于公司没有出现问题的那几部(GN9000L,4.4.2_vivoXplay,6.0.1_MiNote2)真机，只能在wetest上测试，自己的技术有限一直弄不好。等这几部手机没人占用是，我在测试，贴上日志。谢谢您的帮助。

**Comment by qq839924354** [comment]
刚刚下在最新的源码测试，在gn9000L(金立 ELIFE S5.5L)4.3,   4.3_vivoX3L,   4.4.2_vivoXplay3S,三部手机都出现
java.lang.NullPointerException
	at okhttp3.internal.io.FileSystem$1.sink(FileSystem.java:52)
	at okhttp3.internal.cache.DiskLruCache.rebuildJournal(DiskLruCache.java:395)
	at okhttp3.internal.cache.DiskLruCache.initialize(DiskLruCache.java:245)
	at okhttp3.internal.cache.DiskLruCache.get(DiskLruCache.java:435)
	at okhttp3.Cache.get(Cache.java:194)
	at okhttp3.Cache$1.get(Cache.java:144)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:54)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at com.okhttplib.OkHttpUtil$5.intercept(OkHttpUtil.java:354)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)
使用Volley,和没有封装的okhttp3可以正常获取json.
操作过程在http://pan.baidu.com/s/1nuAhwSD上面。不知是什么问题。

**Comment by MrZhousf** [comment]
请发下测试的版本号

**Comment by qq839924354** [comment]
project.ext.sdkVersion = 25
project.ext.buildTools = '25.0.2'
project.ext.minSdkVersion = 14
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.1'
//        classpath 'me.tatarka:gradle-retrolambda:3.2.0'
//        classpath 'me.tatarka.retrolambda.projectlombok:lombok.ast:0.2.3.a2'
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.0'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.3'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
    tasks.withType(JavaCompile) { options.encoding = "UTF-8" }

}

distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip
dependencies {
    compile project(':okhttp3')
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:25.+'
    compile 'com.jakewharton:butterknife:7.0.1'
    testCompile 'junit:junit:4.12'
    compile 'com.google.code.gson:gson:2.8.0'
}
昨天晚上下的你的源码。

**Comment by qq839924354** [comment]
apply plugin: 'com.android.library'

android {

    compileSdkVersion rootProject.sdkVersion
    buildToolsVersion rootProject.buildTools
    resourcePrefix "okhttp3_"

    defaultConfig {
        targetSdkVersion rootProject.sdkVersion
        minSdkVersion rootProject.minSdkVersion
        versionCode 1
        versionName "2.6.9.2"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    lintOptions {
        abortOnError false
    }

}


dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:25.+'
    compile 'com.squareup.okhttp3:okhttp:3.7.0'
}

**Comment by MrZhousf** [comment]
版本已升级，请更新至com.zhousf.lib:okhttp3:2.6.9.3'
根据错误描述是缓存拦截器出了问题，该版本对缓存重新处理了一下。
由于没有wetest账号没办法测试，所以麻烦你再次测试下，谢谢！

**Comment by qq839924354** [comment]
还是有问题，我找了很久还没找到，BRAND=vivo
TYPE=user
java.lang.NullPointerException
        at okhttp3.internal.io.FileSystem$1.sink(FileSystem.java:52)
        at okhttp3.internal.cache.DiskLruCache.rebuildJournal(DiskLruCache.java:395)
        at okhttp3.internal.cache.DiskLruCache.initialize(DiskLruCache.java:245)
        at okhttp3.internal.cache.DiskLruCache.get(DiskLruCache.java:435)
        at okhttp3.Cache.get(Cache.java:194)
        at okhttp3.Cache$1.get(Cache.java:144)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:54)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at com.okhttplib.OkHttpUtil$5.intercept(OkHttpUtil.java:389)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)

**Comment by MrZhousf** [comment]
你好，版本升级了一下，缓存拦截器采用官方标准的写法，请更新测试！

**Comment by qq839924354** [comment]
测试了vivoXplay3S，vivoX3L异步请求好了，所有的ok.谢谢。
